version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:5000'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pepe123
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgresdb

    ports:
      - '5432:5432'


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - db
